---
# install and setup NRPE and checks

- name: Installation epel repository
  yum: name={{item}} state=latest
  with_items:
   - epel-release
- name: yum update to latest version
  yum: name='*' state=latest

- name: selinux disable
  selinux: state=disabled

- name: selinux runtime permasive 
  action: command /usr/sbin/setenforce 0
  ignore_errors: true
  changed_when: false

- name: Install NRPE and Common Plugins
  yum: name={{ item }} state=present
  become: true
  with_items:
    - nrpe
    - nagios-plugins-load
    - nagios-plugins-nrpe
    - nagios-plugins-uptime
    - nagios-plugins-swap
    - nagios-plugins-procs
    - nagios-plugins-users
    - nagios-plugins-disk
    - nagios-plugins-tcp
    - libsemanage-python

- name: Setup NRPE client configuration
  template:
    src=nrpe.cfg.j2
    dest=/etc/nagios/nrpe.cfg

# Firewalld
- name: Determine if firewalld is in use
  shell: systemctl is-enabled firewalld.service | egrep -qv 'masked|disabled'
  ignore_errors: true
  register: firewalld_in_use
  no_log: true

- name: Determine if firewalld is active
  shell: systemctl is-active firewalld.service | grep -vq inactive
  ignore_errors: true
  register: firewalld_is_active
  no_log: true

- name: Determine if TCP/{{nrpe_tcp_port}} is already active
  shell: firewall-cmd --list-ports | egrep -q "^{{nrpe_tcp_port}}/tcp"
  ignore_errors: true
  register: firewalld_nrpe_tcp_port_exists
  no_log: true

# add firewall rule via firewall-cmd
- name: Add firewall rule for TCP/{{nrpe_tcp_port}} (firewalld)
  command: "{{ item }}"
  with_items:
    - firewall-cmd --zone=public --add-port={{nrpe_tcp_port}}/tcp --permanent
    - firewall-cmd --reload
  ignore_errors: true
  become: true
  when: firewalld_in_use.rc == 0 and firewalld_is_active.rc == 0 and firewalld_nrpe_tcp_port_exists.rc != 0

### end firewall settings ###

- name: Start NRPE service
  command: systemctl restart nrpe.service
  ignore_errors: true

- name: Set NRPE to start on boot
  command: systemctl enable nrpe.service
  ignore_errors: true
